### ISSUE TITLE
Public resource on attachments instead of service ?

### ISSUE THREAD

**Issue by iRyusa** [jpalumickas/uplo#14]
Hi !

Is there any way to mix `isPublic` on `attachments` instead on `services` ?

I've seen that the `isPublic` seem to be used only here : https://github.com/jpalumickas/uplo/blob/faf4193df52430afdf9378b794798eb92efbaefe/packages/server/src/Blob/index.ts#L24-L30

But it doesn't seem to be used outside of here, we have to mix signedUrl/publicUrl based on the attachments.

I could maybe workaround it by defining multiple service : 

```
    services: {
      google: new GCSService({
        isPublic: false,
        credentialsPath: process.env.GCP_CREDENTIALS_PATH || '',
        bucket: process.env.GCS_BUCKET as string
      }),
      googlePublic: new GCSService({
        isPublic: true,
        credentialsPath: process.env.GCP_CREDENTIALS_PATH || '',
        bucket: process.env.GCS_BUCKET as string
      })
    },
```

But I would need to "migrate" the `serviceName` on `FileBlob` :/

**Comment by jpalumickas** [comment]
Hey! Good question! Yes, if you need to have public and private, it's better to use multiple services (like in your example), even I recommend to have different buckets for that (to not mix private & public related files)

**Comment by jpalumickas** [comment]
Can you also describe your case for this? Maybe we can update url function to pass private/public

**Comment by iRyusa** [comment]
I think you're right about it, we shouldn't mix everything in the same bucket. I don't know how we'll handle both bucket as GCP inject the credentials files on the fly, but I guess I'll figured it out.

We have a single bucket for fileUpload, product medias,  etc. Some of these should be publicly available (like avatars), but some other should only be available if you have access to the org/order/...

You can close it if you want it might be a bad practice from our end
